global:
  scrape_interval:     1s
  evaluation_interval: 1s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: nodejs
    static_configs:
      - targets: ['backend-app-1:80']
      - targets: ['backend-app-2:80']
  - job_name: traefik
    static_configs:
      - targets: ['traefik:8080']
