## traefik.yml

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false
    network: traefik_public

entryPoints:
  http:
    address: ":80"

metrics:
  prometheus: {}

api:
  insecure: true

